name: pwnpwn
on:
  pull_request:
  push:
    branches: [master, develop]
jobs:
  test-poc:
    name: bla bla
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: first.yml
      - name: Lets see
        run: ls ./cake
